# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:29
from __future__ import unicode_literals
from django.db import migrations
import csv


def load_movies(apps, schema_editor):
    Movie = apps.get_model("recommender", "Movie")
    csv_PATH = 'u.item'

    with open(csv_PATH, 'r', encoding='latin-1') as f:
        categories = {'fieldnames': ('movie_id', 'title', 'release_date'), 'delimiter': '|'}
        reader = csv.DictReader(f, **categories)
        for row in reader:
            m = Movie(id=row['movie_id'], title=row['title'], release_date=row['release_date'])
            m.save()


def load_users(apps, schema_editor):
    User = apps.get_model("recommender", "User")
    csv_PATH = 'u.user'

    with open(csv_PATH, 'r') as f:
        categories = {'fieldnames': ('user_id', 'age', 'gender'), 'delimiter': '|'}
        reader = csv.DictReader(f, **categories)
        for row in reader:
            u = User(id=row['user_id'], age=row['age'], gender=row['gender'])
            u.save()


def load_ratings(apps, schema_editor):
    Rating = apps.get_model("recommender", "Rating")
    User = apps.get_model("recommender", "User")
    Movie = apps.get_model("recommender", "Movie")
    csv_PATH = 'u.data'

    with open(csv_PATH, 'r') as f:
        categories = {'fieldnames': ('user_id', 'movie_id', 'rating', 'rating_date'), 'delimiter': '\t'}
        reader = csv.DictReader(f, **categories)
        for row in reader:
            u = User.objects.get(id=row['user_id'])
            m = Movie.objects.get(id=row['movie_id'])

            r = Rating(rating=row['rating'], rating_date=row['rating_date'], user=u, movie=m)
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_movies),
        migrations.RunPython(load_users),
        migrations.RunPython(load_ratings),
    ]
