# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:29
from __future__ import unicode_literals
from django.db import migrations
import csv


def load_movies(apps, schema_editor):
    Movie = apps.get_model("recommender", "Movie")
    csv_PATH = 'u.item'

    with open(csv_PATH, 'r', encoding='latin-1') as f:
        categories = {'fieldnames': ('movie_id', 'title', 'release_date'), 'delimiter': '|'}
        reader = csv.DictReader(f, **categories)
        for row in reader:
            m = Movie(row['movie_id'], row['title'], row['release_date'])
            m.save()


def load_users(apps, schema_editor):
    User = apps.get_model("recommender", "User")
    csv_PATH = 'u.user'

    with open(csv_PATH, 'r') as f:
        categories = {'fieldnames': ('user_id', 'age', 'gender'), 'delimiter': '|'}
        reader = csv.DictReader(f, **categories)
        for row in reader:
            u = User(row['user_id'], row['age'], row['gender'])
            u.save()


def load_ratings(apps, schema_editor):
    Rating = apps.get_model("recommender", "Rating")
    csv_PATH = 'u.data'

    with open(csv_PATH, 'r') as f:
        categories = {'fieldnames': ('user_id', 'movie_id', 'rating', 'rating_date'), 'delimiter': '\t'}
        reader = csv.DictReader(f, **categories)
        for row in reader:
            # Erros is thrown bc some user_id was null
            # table is header is formatted funny id, rating, rating_date, movie_id, user_id
            # I need an id gerated
            r = Rating(row['rating'], row['rating_date'], row['user_id'], row['movie_id'])
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_movies),
        migrations.RunPython(load_users),
        migrations.RunPython(load_ratings),
    ]
